### Esercitazione 3 Marzo 2026

## Esercizio 0
- Costruire due array numpy-array 2d di dimensione 3000x3000 i cui valori sono campionati da una distribuzione gaussiana con media 0 e varianza 1.
- Effetuare la somma tra le due matrici con due metodi:

        -  utilizzando le operazioni vettoriali 
        -  considerando due cicli espliciti annidati, su righe e colonne
- Confrontare le prestazioni in termini di tempo di esecuzione (utilizzando perf_counter() del modulo time)
        


In [2]:
import numpy as np
import time

arr1 = np.random.randn(3000, 3000)
arr2 = np.random.randn(3000, 3000)

start = time.perf_counter()
arrS1 = arr1 + arr2
print(f"Performance somma Numpy: {time.perf_counter() - start}")

start = time.perf_counter()
arrS2 = []
# for n in arr1:
#     for m in arr2:
#         arrS2.append(n+m)
print(f"Performance somma standard: {time.perf_counter() - start}")



Performance somma Numpy: 0.016474899999593617
Performance somma standard: 5.3699999625678174e-05


## Esercizio 1
- Costruire il NumPy array `s` formato da 40 valori equidistanti nell'intervallo `[0, 20]` (inclusi gli estremi).
- Eseguire il `reshape` di `s` in un array 2D che abbia 4 righe e un numero opportuno di colonne.
- Verificare, usando l'attributo `.base`, se l'array risultante dal `reshape` è una vista o una copia dell'array originale.

In [3]:
import numpy as np

s = np.random.uniform(0, 20, 40)
s2 = s.reshape((4, -1))
print('View' if len(s2.base) else 'Copia')

View


## Esercizio 2
-     Costruire il numpy array t formato da 100 valori equidistanti in `[0, 4]`
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [4]:
import numpy as np

t = np.random.uniform(0, 4, 100)
tR = t.reshape((-1, 4))
print(tR)

[[3.15103444 2.90273232 0.17549846 2.85902391]
 [1.45112061 1.30753136 0.24865367 0.70725422]
 [0.74698774 0.10358553 0.77530529 0.96946884]
 [0.07298945 1.39528098 0.6422519  0.33391714]
 [1.70119358 3.26634258 3.71490865 2.44991185]
 [2.1615729  1.90132361 1.15781705 0.85697468]
 [2.52578638 0.51039788 3.83037218 1.64098863]
 [0.90599655 0.09911233 1.24021951 3.31189692]
 [3.42428561 3.05620073 3.92952977 3.84498553]
 [2.42775537 1.25097958 3.37595403 0.3991678 ]
 [0.79275254 2.83407161 2.20364665 1.08694436]
 [0.58353741 2.33458384 0.98647864 3.5830503 ]
 [2.46592542 0.8312589  2.26692945 1.50944546]
 [1.29776543 0.78321204 1.68945138 3.08682342]
 [1.86589994 0.04440701 3.59030866 2.2410097 ]
 [0.79449341 3.29094533 1.67893244 2.08974787]
 [3.11533093 2.34579578 0.55329822 3.23516393]
 [1.57151795 1.65504417 3.63876862 2.42730807]
 [3.06993049 2.02245262 3.93299903 2.29262452]
 [0.81730182 0.62364037 0.05179463 1.09881674]
 [3.53805262 3.4235682  1.64660887 0.41585637]
 [2.11537307 

## Esercizio 3
- Creare un array NumPy 2D `A` di dimensione 5x6 contenente valori interi da 0 a 29.
- Estrarre:
    - la terza riga;
    - la seconda colonna;
    - il blocco centrale formato dalle righe 2–4 e colonne 2–5;
    - la matrice `A` con le colonne in ordine inverso.
- Stampare ogni risultato e osservarne la forma (`shape`).

In [5]:
import numpy as np

A = np.random.randint(0, 30, (5, 6))
print(A)
print("--- terza riga ---")
print(A[2])
print("--- seconda colonna ---")
print(A[:,1])
print("--- righe 2-4 colonne 2-5 ---")
print(A[2:4,2:5])
print("--- colonne ordine inverso ---")
print(A[:,::-1])

[[21  2 28 16  4 14]
 [ 4  0 16 21 27  4]
 [28 28 19  9 16 10]
 [23 26 22 16 17 20]
 [24  6  8  2 21 29]]
--- terza riga ---
[28 28 19  9 16 10]
--- seconda colonna ---
[ 2  0 28 26  6]
--- righe 2-4 colonne 2-5 ---
[[19  9 16]
 [22 16 17]]
--- colonne ordine inverso ---
[[14  4 16 28  2 21]
 [ 4 27 21 16  0  4]
 [10 16  9 19 28 28]
 [20 17 16 22 26 23]
 [29 21  2  8  6 24]]


## Esercizio 4
Costruire il numpy array 1d C  di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente).  

In [6]:
import numpy as np

C = np.arange(15, 41, 2)
print(C)
C.resize((7, 2))
print(C)

[15 17 19 21 23 25 27 29 31 33 35 37 39]
[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39  0]]


 ## Esercizio 5
 Creare un array NumPy di 10 numeri interi casuali tra 1 e 100.
 

In [7]:
import numpy as np

print(np.random.randint(1, 101, 10))

[56 90  3 35 30 87 70 88 11 91]


 ## Esercizio 6
 Eseguire uno shuffle degli elementi di un numpy-array di 30 numeri interi casuali tra 100 e 200.


In [8]:
import numpy as np

arr = np.random.randint(100, 201, 30)
print(arr)
np.random.shuffle(arr)
print(arr)

[106 155 192 101 174 131 118 167 147 164 130 132 177 170 110 167 131 136
 117 161 174 170 124 166 126 188 191 192 144 111]
[161 192 144 147 111 118 167 117 130 192 131 170 136 188 166 174 126 101
 177 170 155 191 174 132 164 110 124 167 106 131]


  ## Esercizio 7
 Creare una permutazione casuale degli elementi di un numpy-array di 20 valori campionati da una distribuzione  gaussiana con media zero e varianza 1, senza modificare l'array di partenza.

In [9]:
import numpy as np

arr = np.random.randn(20)
print(arr)
arrPermutation = np.random.permutation(arr)
print(arrPermutation)

[ 0.22522716  0.12823782 -0.43741087 -0.28440201 -0.14851235 -1.75289069
 -0.48010097 -0.55645121  0.77467086 -2.08605609  0.73908141 -0.08864159
  1.80267337  0.387709   -2.26937577 -0.19310261  0.88856319  0.46910695
 -0.46972043  0.84767395]
[-0.46972043 -0.14851235 -1.75289069  0.46910695  0.77467086 -2.08605609
 -0.19310261  0.12823782 -0.43741087 -2.26937577  0.88856319 -0.28440201
  0.22522716 -0.48010097  0.387709    0.73908141  0.84767395 -0.08864159
 -0.55645121  1.80267337]


 ## Esercizio 8
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [10]:
import numpy as np

A = np.arange(10, 19).reshape((3, 3))
flatA = A.ravel()
print(flatA.base)
print('View' if (flatA.base is not None) else 'Copia')

[10 11 12 13 14 15 16 17 18]
View


## Esercizio 9
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [11]:
import numpy as np
import utils

A = np.arange(10, 19).reshape((3,3))
flatA = A.flatten()
print('View' if utils.isView(flatA) else 'Copia')


Copia


 ## Esercizio 10
-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [12]:
import numpy as np

f1 = np.arange(0, 16)
f2 = np.arange(16, 32)

f1_4x4 = f1.reshape((4, 4))
f2_4x4 = f2.reshape((4, 4))

f3 = f1_4x4 * f2_4x4
print(f3)

[[  0  17  36  57]
 [ 80 105 132 161]
 [192 225 260 297]
 [336 377 420 465]]


## Esercizio 11
Costruire:
 -     Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 -  `"Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B`


In [13]:
import numpy as np

A = np.random.randn(2, 10)
B = np.arange(0, 20)

print(A.ravel() + B)

[-0.15952963  0.79884212  0.84526061  2.96454669  4.16789534  4.67868602
  6.0339677   8.38198502  9.33872232  9.14844598  8.67800813 11.53190159
 12.66750786 13.71443948 13.93681608 15.58964167 16.24853182 17.30970516
 19.16994116 18.37627872]


## Esercizio 12
-     Costruire f, un numpy array 1D , di shape (10,) costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [14]:
import numpy as np

f = np.linspace(0, 1, 10, dtype=float)

print(f.reshape((1, 10)))

[[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
  0.66666667 0.77777778 0.88888889 1.        ]]


## Esercizio 13
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe

In [15]:
import numpy as np

a = np.arange(14, 10, -1)
# b = np.concatenate((np.arange(4, 0, -1), np.arange(9, 13))).reshape((2, 4))
b = np.vstack((np.arange(4, 0, -1), np.arange(9, 13)))

print(a)
print(b)
print(np.vstack((a, b)))

[14 13 12 11]
[[ 4  3  2  1]
 [ 9 10 11 12]]
[[14 13 12 11]
 [ 4  3  2  1]
 [ 9 10 11 12]]


## Esercizio 14
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
- Costruire il numpy array che si ottiene concatenando a e b per colonne

In [16]:
import numpy as np

a = np.array([14,13,12,11])
b = np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

print(a)
print(b)

print(np.hstack((a.reshape((-1, 1)), b)))

[14 13 12 11]
[[ 4  3  2  1]
 [ 9 10 11 12]
 [ 4  3  2  1]
 [ 9 10 11 12]]
[[14  4  3  2  1]
 [13  9 10 11 12]
 [12  4  3  2  1]
 [11  9 10 11 12]]


## Esercizio 15
Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale principale, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

In [17]:
import numpy as np

A = np.diag([10] * 10) + np.diag([-12] * 9, -1) + np.diag([-2] * 9, 1)
print(A)
# volendo anche ma è da specificare il tipo: print(np.eye(10, k=-1, dtype=int) * -12 + np.eye(10, k=1, dtype=int) * -2 + np.eye(10, dtype=int) * 10)

[[ 10  -2   0   0   0   0   0   0   0   0]
 [-12  10  -2   0   0   0   0   0   0   0]
 [  0 -12  10  -2   0   0   0   0   0   0]
 [  0   0 -12  10  -2   0   0   0   0   0]
 [  0   0   0 -12  10  -2   0   0   0   0]
 [  0   0   0   0 -12  10  -2   0   0   0]
 [  0   0   0   0   0 -12  10  -2   0   0]
 [  0   0   0   0   0   0 -12  10  -2   0]
 [  0   0   0   0   0   0   0 -12  10  -2]
 [  0   0   0   0   0   0   0   0 -12  10]]


## Esercizio 16
Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

In [18]:
import numpy as np

I = np.eye(*A.shape, dtype=int)
print(I)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


## Esercizio 17
Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?

In [19]:
import utils

AA = A[2:9:2, 3:6:2]
print(AA)
utils.printIsView(AA)


[[ -2   0]
 [-12  -2]
 [  0 -12]
 [  0   0]]
View


## Esercizio 18
Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

In [21]:
from utils import printIsView
A1 = A[:,1:5:2]
print(A1)
printIsView(A1)
A1copy = A1.copy()
printIsView(A1copy)

[[ -2   0]
 [ 10   0]
 [-12  -2]
 [  0  10]
 [  0 -12]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]
 [  0   0]]
View
Copy


## Esercizio 19

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A/B   dove  $\quad f_{ij}=a_{ij}/b_{ij} \quad i=0,..,n, \quad j=0,...,n$

In [24]:
import numpy as np

A = np.random.randint(1, 21, (5,5))
B = np.random.randint(1, 7, (5, 5))

C = A + B
D = A - B
E = A * B
F = A / B

## Esercizio 20
Dato array NumPy che rappresenta le vendite giornaliere di un negozio per un mese,
vendite = np.random.randint(50, 200, 30) 

        Trova tutti i giorni in cui le vendite sono state superiori a 150.

        Calcola la media delle vendite solo per i giorni in cui sono state superiori a 150.

        Imposta le vendite a 0 per tutti i giorni in cui sono state inferiori a 100.


In [35]:
import numpy as np

vendite = np.random.randint(50, 200, 30)
venditeFiltered = vendite[vendite > 150]
print(np.average(venditeFiltered))
vendite[vendite < 100] = 0 # Posso farlo perché lo slicing crea una copia
print(vendite)

180.44444444444446
[140 135 190 104   0 142 136 198 184 145   0 150 123 125 122 173 191   0
 130   0 175   0 151   0 172 190   0   0 132   0]


## Esercizio 21
Costruisci A, un numpy array 2d di shape (3,3) e b,  un numpy array 2d di shape (3,1)
e somma b ad ogni colonna di A b


In [46]:
A = np.random.randint(1, 11, (3, 3))
b = np.random.randint(-11, -1, (3, 1))
print(A)
print(b)
print(A + b) # Numpy si accorge che il vettore b ha una dimensione compatibile con A, quindi fa il broadcast

[[3 3 2]
 [5 7 7]
 [1 1 8]]
[[ -9]
 [ -4]
 [-10]]
[[-6 -6 -7]
 [ 1  3  3]
 [-9 -9 -2]]


# Esercizio 22
dato il numpy array 2d G=np.linspace(0,10,20).reshape(-1,4), scambiare in G la seconda riga con la quarta riga

## Esercizio 23
Visualizzare il grafico della funzione $f(x)=sin^2(x)/x$ in 200 punti equidistanti nell'intervallo $[0.1,2\pi]$

## Esercizio 24
- Costruire un numpy array 1d di 16 valori equidistanti nell'intervallo [0,4].
- Costruire il  numpy array 2d ottenuto facendo un reshape a (4,4) di quest'ultimo.
- Costruire un numpy array 1d di 4 valori  interi casuali nell'intervallo [10,60]
- costruire il prodotto scalare A per b, usando A@b, e vettorizzando solo il ciclo interno.


## Esercizio 25
Dato g un numpy array 2d, estendilo di una riga in alto ed di una riga in basso, di una colonna a sinistra ed di una colonna a destra, usa la funzione g_est= np.pad(g,(1,1),mode='reflect'). Visualizza 'g_est' e commenta cosa vedi.

## Esercizio 26
Scrivi un programma Python che esegua l'elaborazione di un'immagine utilizzando un filtro di media. 

Utilizza il padding per gestire i pixel del bordo durante l'applicazione del filtro.

Il programma deve seguire questi passaggi:

- Carica l'immagine: Carica l'immagine 'cameraman.png' utilizzando la libreria Matplotlib.**image=plt.imread('cameraman.png')**
- Visualizza l'immagine originale **plt.imshow(image,cmap='gray')**
- definisce la dimensione del filtro, dim_filtro
- Applica il padding: Applica un padding costante di dim_filtro//2 pixel a tutti i bordi dell'immagine (utilizzando il metodo di numpy **image_bordered=np.pad(image,(dim_filtro//2,dim_filtro//2),, mode='reflect')**
- Crea il filtro di media: Crea un filtro di media di dimensioni *dim_filtroxdim_filtro*, dove tutti gli elementi sono pari a 1/(dim_filtroxdim_filtro)
- Applica il filtro: Scorri ogni pixel dell'immagine con padding (escludendo i bordi aggiunti) e applica il filtro di media.

   *Per ogni pixel, calcola la somma dei prodotti tra i pixel della sottomatrice dim_filtroxdim_filtro centrata sul pixel corrente e il filtro.*
   
- Crea l'immagine filtrata: Crea un nuovo array NumPy che rappresenta l'immagine filtrata, dove ogni pixel contiene il risultato dell'applicazione del filtro.
- Visualizza l'immagine filtrata: Visualizza l'immagine filtrata utilizzando Matplotlib con la mappa di colori 'gray'.
- Aggiungi una colorbar per visualizzare la scala dei valori dell'immagine filtrata.
- Mostra l'immagine filtrata con Matplotlib.


Requisiti:

-  Utilizzare la libreria Matplotlib per caricare e visualizzare l'immagine.
-  Utilizzare la libreria NumPy per la manipolazione degli array e per il padding.