### Esercitazione 3 Marzo 2026

## Esercizio 0
- Costruire due array numpy-array 2d di dimensione 3000x3000 i cui valori sono campionati da una distribuzione gaussiana con media 0 e varianza 1.
- Effetuare la somma tra le due matrici con due metodi:

        -  utilizzando le operazioni vettoriali 
        -  considerando due cicli espliciti annidati, su righe e colonne
- Confrontare le prestazioni in termini di tempo di esecuzione (utilizzando perf_counter() del modulo time)
        


In [50]:
import numpy as np
import time

arr1 = np.random.randn(3000, 3000)
arr2 = np.random.randn(3000, 3000)

start = time.perf_counter()
arrS1 = arr1 + arr2
print(f"Performance somma Numpy: {time.perf_counter() - start}")

start = time.perf_counter()
arrS2 = []
for n in arr1:
    for m in arr2:
        arrS2.append(n+m)
print(f"Performance somma standard: {time.perf_counter() - start}")



Performance somma Numpy: 0.5206218060002357


KeyboardInterrupt: 

## Esercizio 1
- Costruire il NumPy array `s` formato da 40 valori equidistanti nell'intervallo `[0, 20]` (inclusi gli estremi).
- Eseguire il `reshape` di `s` in un array 2D che abbia 4 righe e un numero opportuno di colonne.
- Verificare, usando l'attributo `.base`, se l'array risultante dal `reshape` è una vista o una copia dell'array originale.

In [ ]:
import numpy as np

s = np.random.uniform(0, 20, 40)
s2 = s.reshape((4, -1))
print('View' if len(s2.base) else 'Copia')

View


## Esercizio 2
-     Costruire il numpy array t formato da 100 valori equidistanti in `[0, 4]`
-     considerarne il reshape in un array 2d che ha 4 colonne con un numero opportuno di righe

In [ ]:
import numpy as np

t = np.random.uniform(0, 4, 100)
tR = t.reshape((-1, 4))
print(tR)

[[2.28510879 0.99824846 1.25519202 3.23791129]
 [2.74070297 1.82747376 1.47600381 1.99620239]
 [3.80977368 0.52263609 2.33483897 1.17695523]
 [3.9501204  2.87450623 2.04052593 2.5530747 ]
 [0.04889284 3.77268843 2.43077425 3.48750308]
 [2.74800705 3.41224742 0.67558389 3.21733352]
 [1.98915539 3.48455687 1.38821873 2.24655828]
 [2.50714719 2.46220807 1.66888378 0.18324415]
 [0.15673154 1.26278133 3.53394805 3.57149742]
 [0.53159629 2.3054233  2.29410528 1.97499539]
 [0.41207645 2.02317406 2.93287497 2.6122119 ]
 [0.26485802 1.68893623 0.90156773 1.45835981]
 [2.92063101 2.37379323 1.95940009 3.35289165]
 [3.24732635 1.05296712 2.00914815 2.02687482]
 [1.27936441 3.54533071 3.27842706 3.3192896 ]
 [0.07631153 0.9052449  1.58569797 2.01425623]
 [3.54566642 3.05635741 3.03246008 2.25930765]
 [1.04802452 1.33653281 2.98598506 3.44359602]
 [1.59871474 0.25307961 2.64599489 1.56331732]
 [1.68698084 1.48591499 2.36539554 1.4895552 ]
 [2.41698036 0.51942887 1.54586611 0.96333366]
 [2.461721   

## Esercizio 3
- Creare un array NumPy 2D `A` di dimensione 5x6 contenente valori interi da 0 a 29.
- Estrarre:
    - la terza riga;
    - la seconda colonna;
    - il blocco centrale formato dalle righe 2–4 e colonne 2–5;
    - la matrice `A` con le colonne in ordine inverso.
- Stampare ogni risultato e osservarne la forma (`shape`).

In [ ]:
import numpy as np

A = np.random.randint(0, 30, (5, 6))
print(A)
print("--- terza riga ---")
print(A[2])
print("--- seconda colonna ---")
print(A[:,1])
print("--- righe 2-4 colonne 2-5 ---")
print(A[2:4,2:5])
print("--- colonne ordine inverso ---")
print(A[:,::-1])

[[19 29 20 25  7 10]
 [19  6 12 24  4  9]
 [ 5  4  5 14  9 26]
 [ 3 18  9  4 21  1]
 [ 2  5 10  5 16  1]]
--- terza riga ---
[ 5  4  5 14  9 26]
--- seconda colonna ---
[29  6  4 18  5]
--- righe 2-4 colonne 2-5 ---
[[ 5 14  9]
 [ 9  4 21]]
--- colonne ordine inverso ---
[[10  7 25 20 29 19]
 [ 9  4 24 12  6 19]
 [26  9 14  5  4  5]
 [ 1 21  4  9 18  3]
 [ 1 16  5 10  5  2]]


## Esercizio 4
Costruire il numpy array 1d C  di valori che variano tra 15 e 41 con step 2

-     Trasformarlo in un numpy array 2d con shape(7,2) usando il metodo . resize(7,2)  che lavora in-place,  (cioè  modifica l'array esistente).  

In [ ]:
import numpy as np

C = np.arange(15, 41, 2)
print(C)
C.resize((7, 2))
print(C)

[15 17 19 21 23 25 27 29 31 33 35 37 39]
[[15 17]
 [19 21]
 [23 25]
 [27 29]
 [31 33]
 [35 37]
 [39  0]]


 ## Esercizio 5
 Creare un array NumPy di 10 numeri interi casuali tra 1 e 100.
 

In [ ]:
import numpy as np

print(np.random.randint(1, 101, 10))

[19 95 72 37 94 18 83 28 86 52]


 ## Esercizio 6
 Eseguire uno shuffle degli elementi di un numpy-array di 30 numeri interi casuali tra 100 e 200.


In [ ]:
import numpy as np

arr = np.random.randint(100, 201, 30)
print(arr)
np.random.shuffle(arr)
print(arr)

[187 194 142 117 100 197 129 118 127 154 130 127 146 114 115 158 130 123
 116 170 115 197 153 174 129 198 158 196 106 145]
[197 153 174 106 130 127 127 146 118 145 158 194 116 115 158 123 117 129
 142 197 114 130 129 196 115 187 170 154 198 100]


  ## Esercizio 7
 Creare una permutazione casuale degli elementi di un numpy-array di 20 valori campionati da una distribuzione  gaussiana con media zero e varianza 1, senza modificare l'array di partenza.

In [51]:
import numpy as np

arr = np.random.randn(20)
print(arr)
arrPermutation = np.random.permutation(arr)
print(arrPermutation)

[-0.87796428 -0.53848762 -0.04093462 -0.1239018   0.8808187   0.5560542
  0.30779894  1.03907049 -0.25977407 -1.11475011  0.60488791  0.15050347
  0.20692274  1.00140675 -1.10555271  0.79751569 -1.04114703  0.11369398
 -1.56452305 -0.66186383]
[ 0.30779894  1.03907049 -0.25977407 -0.04093462 -1.11475011  0.11369398
 -0.1239018   0.5560542  -0.53848762  0.15050347 -1.04114703  0.20692274
 -1.10555271  0.60488791  1.00140675 -0.66186383  0.8808187   0.79751569
 -1.56452305 -0.87796428]


 ## Esercizio 8
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo .ravel()  
-     Si tratta di una copia o di una vista?

In [68]:
import numpy as np

A = np.arange(10, 19).reshape((3, 3))
flatA = A.ravel()
print(flatA.base)
print('View' if (flatA.base is not None) else 'Copia')

[10 11 12 13 14 15 16 17 18]
View


## Esercizio 9
-     Scrivere il numpy  array 2d, A, [[10,11,12],[13,14,15],[16,17,18]] 
-     trasformarlo in un numpy array 1d usando il metodo  .flatten().
-     Si tratta di una copia o di una vista?

In [71]:
import numpy as np
import utils

A = np.arange(10, 19).reshape((3,3))
flatA = A.flatten()
print('View' if utils.isView(flatA) else 'Copia')


Copia


 ## Esercizio 10
-     creare i due  numpy array 1d
        f1= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]  
        f2= [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
-     "vederli" come matrici  4x4 ed effettuarne il prodotto scalare, memorizzando in f3 la matrice che nasce dal loro prodotto.

In [73]:
import numpy as np

f1 = np.arange(0, 16)
f2 = np.arange(16, 32)

f1_4x4 = f1.reshape((4, 4))
f2_4x4 = f2.reshape((4, 4))

f3 = f1_4x4 * f2_4x4
print(f3)

[[  0  17  36  57]
 [ 80 105 132 161]
 [192 225 260 297]
 [336 377 420 465]]


## Esercizio 11
Costruire:
 -     Numpy Array A di shape (2,10) : array di valori random campionati da una distribuzione gaussiana con media 0 e varianza 1.
 -     Numpy array 1D B di shape (20,) formato dagli interi da 0 a 19.
 
 -  `"Vedere" A come un array 1D di 20 elementi ed effettuare la somma di A+B`


In [77]:
import numpy as np

A = np.random.randn(2, 10)
B = np.arange(0, 20)

print(A.ravel() + B)

[ 0.57639472  2.67006021  1.49976995  4.14507874  4.72133071  6.6115661
  6.1948979   6.85734094  7.72936697  8.28042499 11.65763773 10.64251958
 11.10167547 12.82235204 13.44865341 15.79651785 15.88846471 17.38879305
 15.90152919 18.22064428]


## Esercizio 12
-     Costruire f, un numpy array 1D , di shape (10,) costituito da 10 valori equidistanti nell'intervallo [0,1]
-     aumentarne la dimensionalità, in maniera tale che abbia shape (10,1)

In [80]:
import numpy as np

f = np.linspace(0, 1, 10, dtype=float)

print(f.reshape((1, 10)))

[[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
  0.66666667 0.77777778 0.88888889 1.        ]]


## Esercizio 13
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12]])

  Costruire il numpy array che si ottiene concatenando a e b per righe

In [93]:
import numpy as np

a = np.arange(14, 10, -1)
# b = np.concatenate((np.arange(4, 0, -1), np.arange(9, 13))).reshape((2, 4))
b = np.vstack((np.arange(4, 0, -1), np.arange(9, 13)))

print(a)
print(b)
print(np.vstack((a, b)))

[14 13 12 11]
[[ 4  3  2  1]
 [ 9 10 11 12]]
[[14 13 12 11]
 [ 4  3  2  1]
 [ 9 10 11 12]]


## Esercizio 14
-     Costruire i seguenti numpy array
      a= np.array([14,13,12,11])
      b=np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])
- Costruire il numpy array che si ottiene concatenando a e b per colonne

In [17]:
import numpy as np

a = np.array([14,13,12,11])
b = np.array([[4,3,2,1],[9,10,11,12],[4,3,2,1],[9,10,11,12]])

print(a)
print(b)

print(np.hstack((a.reshape((-1, 1)), b)))

[14 13 12 11]
[[ 4  3  2  1]
 [ 9 10 11 12]
 [ 4  3  2  1]
 [ 9 10 11 12]]
[[14  4  3  2  1]
 [13  9 10 11 12]
 [12  4  3  2  1]
 [11  9 10 11 12]]


## Esercizio 15
Costruire, facendo uso di una sola riga di codice, la matrice A di ordine 10, che ha gli unici elementi diversi da zero, sulla diagonale principale, sulla codiagonale inferiore e sulla codiagonale superiore:

elementi diagonali $A_{i,i}=10 \quad$, i=1,20

elementi nella codiagonale inferiore $A_{i-1,i}=-12, \quad$ i=2,..,20, 

elementi nella codiagonale superiore $A_{i,i+1}=-2 \quad$ i=1,..,19

## Esercizio 16
Costruire la matrice identità, denominata *I*,  della stessa dimensione di *A*

## Esercizio 17
Facendo uso dell'operatore slicing *:* ,costruire la matrice AA selezionando dalla matrice A le righe che vanno dalla 2 alla 9 con step 2 e le colonne che vanno dalla 3 alla 6 con step 2.
La matrice AA è una vista o una copia?

## Esercizio 18
Facendo uso dell'operatore slicing *:*, costruire la matrice A1 selezionando dalla matrice A le colonne che vanno dalla 1 alla 5 con step 2.  Trasforma la matrice A1 in una copia.

## Esercizio 19

Costruisci due numpy array A e B di shape (5,5) 
   - A formata da numeri interi casuali  nell'intervallo [1,20]
   - B formata da numeri interi casuali  nell'intervallo [1,6]
 
  Costruisci con una sola riga di codice le seguenti matrici
  
  C=A+B   dove  $\quad c_{ij}=a_{ij}+b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  D=A-B   dove  $\quad d_{ij}=a_{ij}-b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  E=A*B   dove  $\quad e_{ij}=a_{ij}*b_{ij} \quad i=0,..,n, \quad j=0,...,n$
  
  F=A/B   dove  $\quad f_{ij}=a_{ij}/b_{ij} \quad i=0,..,n, \quad j=0,...,n$

## Esercizio 20
Dato array NumPy che rappresenta le vendite giornaliere di un negozio per un mese,
vendite = np.random.randint(50, 200, 30) 

        Trova tutti i giorni in cui le vendite sono state superiori a 150.

        Calcola la media delle vendite solo per i giorni in cui sono state superiori a 150.

        Imposta le vendite a 0 per tutti i giorni in cui sono state inferiori a 100.


## Esercizio 21
Costruisci A, un numpy array 2d di shape (3,3) e b,  un numpy array 2d di shape (3,1)
e somma b ad ogni colonna di A b


# Esercizio 22
dato il numpy array 2d G=np.linspace(0,10,20).reshape(-1,4), scambiare in G la seconda riga con la quarta riga

## Esercizio 23
Visualizzare il grafico della funzione $f(x)=sin^2(x)/x$ in 200 punti equidistanti nell'intervallo $[0.1,2\pi]$

## Esercizio 24
- Costruire un numpy array 1d di 16 valori equidistanti nell'intervallo [0,4].
- Costruire il  numpy array 2d ottenuto facendo un reshape a (4,4) di quest'ultimo.
- Costruire un numpy array 1d di 4 valori  interi casuali nell'intervallo [10,60]
- costruire il prodotto scalare A per b, usando A@b, e vettorizzando solo il ciclo interno.


## Esercizio 25
Dato g un numpy array 2d, estendilo di una riga in alto ed di una riga in basso, di una colonna a sinistra ed di una colonna a destra, usa la funzione g_est= np.pad(g,(1,1),mode='reflect'). Visualizza 'g_est' e commenta cosa vedi.

## Esercizio 26
Scrivi un programma Python che esegua l'elaborazione di un'immagine utilizzando un filtro di media. 

Utilizza il padding per gestire i pixel del bordo durante l'applicazione del filtro.

Il programma deve seguire questi passaggi:

- Carica l'immagine: Carica l'immagine 'cameraman.png' utilizzando la libreria Matplotlib.**image=plt.imread('cameraman.png')**
- Visualizza l'immagine originale **plt.imshow(image,cmap='gray')**
- definisce la dimensione del filtro, dim_filtro
- Applica il padding: Applica un padding costante di dim_filtro//2 pixel a tutti i bordi dell'immagine (utilizzando il metodo di numpy **image_bordered=np.pad(image,(dim_filtro//2,dim_filtro//2),, mode='reflect')**
- Crea il filtro di media: Crea un filtro di media di dimensioni *dim_filtroxdim_filtro*, dove tutti gli elementi sono pari a 1/(dim_filtroxdim_filtro)
- Applica il filtro: Scorri ogni pixel dell'immagine con padding (escludendo i bordi aggiunti) e applica il filtro di media.

   *Per ogni pixel, calcola la somma dei prodotti tra i pixel della sottomatrice dim_filtroxdim_filtro centrata sul pixel corrente e il filtro.*
   
- Crea l'immagine filtrata: Crea un nuovo array NumPy che rappresenta l'immagine filtrata, dove ogni pixel contiene il risultato dell'applicazione del filtro.
- Visualizza l'immagine filtrata: Visualizza l'immagine filtrata utilizzando Matplotlib con la mappa di colori 'gray'.
- Aggiungi una colorbar per visualizzare la scala dei valori dell'immagine filtrata.
- Mostra l'immagine filtrata con Matplotlib.


Requisiti:

-  Utilizzare la libreria Matplotlib per caricare e visualizzare l'immagine.
-  Utilizzare la libreria NumPy per la manipolazione degli array e per il padding.